---
# tasks file for nginx
- name: set timezone
  command:
    cmd: /usr/bin/timedatectl set-timezone Australia/Sydney

- name: install nginx
  apt: 
    name: nginx 
    state: present
- tags: ['packages']

- name: configure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/app mode=0644
  notify: restart nginx
- tags: ['configure']

- name: get active sites
  shell: ls -l /etc/nginx/sites-enabled/
  register: active
  changed_when: "active.stdout_lines != sites.keys()"
- tags: ['configure']

- name: de-activate default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- tags: ['configure']

- name: activate nginx site
  file: src=/etc/nginx/sites-available/app dest=/etc/nginx/sites-enabled/app state=link
  notify: restart nginx
- tags: ['configure']

- name: ensure nginx started
  service:
    name: nginx
    state: started
    enabled: yes
- tags: ['configure']
