---
# tasks file for apache2
- name: set timezone
  command:
    cmd: /usr/bin/timedatectl set-timezone Australia/Sydney
  tags: ['configure']

- name: install webserver components
  apt:
    pkg:
    - apache2
    - libapache2-mod-wsgi-py3
    state: present
  tags: ['packages']

- name: ensure apache2 started
  service: name=apache2 state=started enabled=yes
  tags: ['configure']

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  notify: restart apache2
  tags: ['configure']
