---
# tasks file for control
- name: install control components
  apt:
    pkg:
    - curl
    - mysql-client
    state: present
- name: set timezone
  command:
    cmd: /usr/bin/timedatectl set-timezone Australia/Sydney

- tags: ['control']
