---
# tasks file for mysql
- name: set timezone
  command:
    cmd: /usr/bin/timedatectl set-timezone Australia/Sydney
  tags: ['configure']

- name: install mysql
  apt: 
    pkg: mysql-server 
    state: present
  tags: ['packages']

- name: ensure mysql started
  service: name=mysql state=started enabled=yes
  tags: ['configure']

- name: install mysql tools
  apt:
    pkg:
    - mysql-client
    - python3-pymysql
  tags: ['packages']

- name: change the authentication plugin of mysql root user to mysql_native_password
  shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'
  tags: ['configure']

- name: flush privileges
  shell: mysql -u root -e 'FLUSH PRIVILEGES'
  tags: ['configure']

- name: set mysql root password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: ''
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present
  no_log: true
  tags: ['configure']

- name: ensure mysql listening on all ports
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: ^bind-address
    line: bind-address = "{{ ansible_all_ipv4_addresses[1] }}"
    notify: restart mysql
  tags: ['configure']

- name: create app user
  mysql_user:
    login_user: 'root'
    login_password: '{{ mysql_root_password }}'
    name: '{{ app_svc }}'
    password: '{{ app_pw }}'
    host: '%'
    priv: '*.*:ALL'
    state: present
  no_log: true
  tags: ['configure']

- name: create ~/.my.cnf
  file:
    path: ~/.my.cnf
    state: touch
  no_log: true
  tags: ['configure']

- name: insert into ~/.my.cnf
  blockinfile:
    path: ~/.my.cnf
    block: |
      [client]
      user={{ app_svc }}
      password={{ app_pw }}
  no_log: true
  tags: ['configure']

- name: create app database
  mysql_db:
    login_user: '{{ app_svc }}'
    login_password: '{{ app_pw }}'
    name: '{{ app_db }}'
  tags: ['configure']
