---
# Bring stack down

# Stop Load Balancer
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=stopped

# Stop Web Server
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=stopped

# Restart Database Server
- hosts: database
  become: true
  tasks:
    - service: name=nginx state=restarted

# Bring stack back up

# Start Web Server
- hosts: webserver
  become: true
  tasks:
    - service: name=apache2 state=started

#Start Load Balancer
- hosts: loadbalancer
  become: true
  tasks:
    - service: name=nginx state=started

